version: '3.8'

services:
  backend:
    build:
      context: ./Backend/FlightSearch_KingICT
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - AMADEUS_API_KEY=${AMADEUS_API_KEY}
      - AMADEUS_API_SECRET=${AMADEUS_API_SECRET}
    depends_on:
      - redis
    restart: on-failure

  frontend:
    build:
      context: ./Frontend/flight-search-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  redis:
    image: redis
    container_name: redis-server-java
    ports:
      - "6379:6379"
